# Generated by Django 3.0.5 on 2020-04-05 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='total_pedido',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True),
        ),
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtos', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='itens_pedido', to='pedidos.Pedidos')),
            ],
            options={
                'verbose_name': 'Item Pedido',
                'verbose_name_plural': 'Itens Pedidos',
            },
        ),
    ]
