# Generated by Django 3.0.5 on 2020-04-05 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20200405_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itenspedido',
            name='pedido',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='item',
            field=models.ManyToManyField(to='pedidos.ItensPedido'),
        ),
    ]
