# Generated by Django 3.0.5 on 2020-04-05 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_auto_20200405_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='item',
        ),
        migrations.AddField(
            model_name='itenspedido',
            name='pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedidos.Pedidos'),
            preserve_default=False,
        ),
    ]
